routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::post('login', '\App\Http\Controllers\Auth\LoginController@authenticate');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('/');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'users', 'middleware' => ['auth'], 'as' => 'users.'], function () {
    Route::get('/', [App\Http\Controllers\UserController::class, 'index'])->name('index');
    Route::get('datatable', [App\Http\Controllers\UserController::class, 'datatable'])->name('datatable');
    Route::get('add', [App\Http\Controllers\UserController::class, 'create'])->name('add');
    Route::post('add/store', [App\Http\Controllers\UserController::class, 'store'])->name('add.store');
    Route::get('edit/{id}', [App\Http\Controllers\UserController::class, 'edit'])->name('edit');
    Route::post('update/{id}', [App\Http\Controllers\UserController::class, 'update'])->name('edit.update');
    Route::delete('delete/{id}', [App\Http\Controllers\UserController::class, 'destroy'])->name('delete');
});

resources/views/layout/footer.blade.php
    @if (!request()->is('login'))
    <footer class="main-footer">
        <strong>Copyright &copy; 2021 <a href="/">SmartChecking</a>.</strong> All rights reserved.
    </footer>
    @endif

</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{{ asset('template/') }}/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('template/') }}/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="{{ asset('template/') }}/dist/js/adminlte.min.js"></script>
<!-- <script src="{{ asset('vendor/holdOn/holdOn.min.js') }}"></script> -->
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/lodash@4.17.20/lodash.min.js"></script>
@toastr_js
@toastr_render
<script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

    $.fn.select2.defaults.set( "theme", "bootstrap4" );

    function loading(message) {
        var options = {
            theme:"sk-circle",
            message: message ?? '<br>Proccessing your data, please wait a moment',
        };

        HoldOn.open(options);
    }
    $('.nav-item').on('click',function () {
        if ($('.nav-item').hasClass('menu-is-opening')) {
            $(this).attr('class','nav-item');
        }
    });
    jQuery('a[data-widget=pushmenu]').click(function(){
        jQuery('.sidebar-mini').toggleClass('sidebar-collapse');
        });

    $('#logout').on('click', function (event) {
    event.preventDefault();
    const url = $(this).attr('href');
    swal({
        title: 'Logout',
        text: 'Apakah anda yakin akan logout?',
        customClass: 'swal-width',
        icon: 'warning',
        buttons: ["Tidak", "Iya"],
    }).then(function(value) {
        if (value) {
            window.location.href = url;
        }
    });
});
</script>

@stack('custom-scripts')

</body>
</html>

resources/views/layout/header.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}" />

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('template/') }}/plugins/fontawesome-free/css/all.min.css">

    @stack('custom-css')

    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('template/') }}/dist/css/adminlte.min.css">


    @toastr_css
    <style>
        .nav-sidebar .menu-is-opening>.nav-link i.right, .nav-sidebar .menu-open>.nav-link i.right{
            transform: rotate(-180deg);
        }
        .swal-modal{
            width: 375px !important;
        }
        .swal-footer{
            text-align: center !important;
        }
        .head-icon{
            size: 10px;
            padding:5px;
        }
    </style>
</head>
<body class="hold-transition sidebar-mini {{ (request()->is('login')) ? 'login-page' : '' }}">

<!-- Site wrapper -->
<div class="{{ (request()->is('login')) ? '' : 'wrapper' }}">

resources/views/layout/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
      </ul>
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item">
        <a class="nav-link" href="javascript:void(0)">
          {{ user()->name }}
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Navbar -->
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/" class="brand-link">
      <img src="{{ asset('template/') }}/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">{{ env('APP_NAME') }}</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->

          <li class="nav-header">Menu</li>
          <li class="nav-item">
            <a href="{{ route('home') }}" class="nav-link">
              <i class="fas fa-home"></i>
              <p>
                Beranda
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('users.index') }}" class="nav-link {{ request()->is('*users*') ? 'active' : '' }}">
              <i class="fas fa-users"></i>
              <p>
                Master Pengguna
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ url()->route('logout') }}" class="nav-link" id="logout">
              <i class="fas fa-sign-out-alt"></i>
              <p>
                Keluar
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

resources/views/layout/template.blade.php
@include('layout.header')

    @if (!request()->is('login'))
        @include('layout.navbar')
    @endif
  
    
    @yield('content')

@include('layout.footer')