routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::post('login', '\App\Http\Controllers\Auth\LoginController@authenticate');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('/');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'users', 'middleware' => ['auth'], 'as' => 'users.'], function () {
    Route::get('/', [App\Http\Controllers\UserController::class, 'index'])->name('index');
    Route::get('datatable', [App\Http\Controllers\UserController::class, 'datatable'])->name('datatable');
    Route::get('add', [App\Http\Controllers\UserController::class, 'create'])->name('add');
    Route::post('add/store', [App\Http\Controllers\UserController::class, 'store'])->name('add.store');
    Route::get('edit/{id}', [App\Http\Controllers\UserController::class, 'edit'])->name('edit');
    Route::post('update/{id}', [App\Http\Controllers\UserController::class, 'update'])->name('edit.update');
    Route::delete('delete/{id}', [App\Http\Controllers\UserController::class, 'destroy'])->name('delete');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\UserRequest;
use App\Models\User;
use DB;
use Auth;
use Carbon\Carbon;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.user.index');
    }

    public function datatable()
    {
        $data = User::all();

        return \DataTables::of($data)
            ->addIndexColumn()
            ->removeColumn('id')
            ->editColumn('created_at', function ($data){
                return Carbon::parse($data->created_at)->timezone('Asia/Jakarta')->format('d-M-Y H:i:s');
            })
            ->addColumn('action', function ($data) {
                
                $action = '<a href="' . route('users.edit', $data->id) . '" class="btn btn-primary btn-xs" data-toggle="tooltip" data-placement="top" title="' . __('Edit user') . '"><i class="fa fa-edit"></i></a>&nbsp;';
                
                if($data->id != 1){
                    $action .= '<form method="post" action="' . route('users.delete', $data->id) . '" style="display: inline">
                    <input type="hidden" name="_token" value="' . csrf_token() . '"><input type="hidden" name="_method" value="delete">
                    <button class="btn btn-danger btn-xs" data-toggle="tooltip" data-placement="top" title="Hapus pengguna ini?" onclick="return confirm(\'' . __('Hapus pengguna ini?') . '\')"><i class="fa fa-trash"></i></button>&nbsp;
                    </form>';
                }

                return '<div class="d-flex">' . $action . '</div>';
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        $redirect = back();
        try {
            DB::beginTransaction();
            $data = [
                'name' => $request->name,
                'email' => $request->email,
                'password' => \Hash::make($request->password),
            ];

            $user = User::create($data);
            $redirect = redirect()->route('users.index');
            toastr()->success('Pengguna baru telah berhasil ditambahkan');
            DB::commit();
        } catch (\Exception $e) {
            \Log::info('Data pengguna baru gagal dibuat detail: ' . substr($e->getMessage(), 0, 1000) . ' at ' . $e->getFile() . ' in line ' . $e->getLine());
            toastr()->error('Gagal menambahkan pengguna !');
            DB::rollback();
        }
        return $redirect;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $check_user = User::find($id);
        if($check_user){
            return view('admin.user.create', ['data' => $check_user]);
        }else{
            toastr()->error('Pengguna tidak ditemukan');
            return redirect()->back();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, $id)
    {
        try {

            $check_user = User::find($id);

            if ($check_user) {
                DB::beginTransaction();

                if ($request->password) {
                    $password = \Hash::make($request->password);
                } else {
                    $password = $check_user->password;
                }
                $check_user->update([
                    'name' => $request->name,
                    'email' => $request->email,
                    'password' => $password,
                ]);
                toastr()->success('Pengguna telah diperbarui');
                DB::commit();
            } else {
                toastr()->error('Pengguna tidak ditemukan');
                DB::rollback();
            }
            return redirect()->route('users.index');
        } catch (\Exception $e) {
            \Log::info('Gagal meperbaharui data pengguna : ' . substr($e->getMessage(), 0, 1000) . ' at ' . $e->getFile() . ' in line ' . $e->getLine());
            toastr()->error('Gagal ubah pengguna !');
            DB::rollback();
        }
        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            DB::beginTransaction();

            if ($check = User::find($id)) {
                if($check->id == 1){
                    toastr()->error('Pengguna tidak diizinkan untuk dihapus');
                    DB::rollback();
                }else{
                    $check->delete();
                    toastr()->success('Pengguna telah dihapus');
                    DB::commit();
                }
            } else {
                toastr()->error('Pengguna tidak ditemukan');
                DB::rollback();
            }
        } catch (\Exception $e) {
            \Log::info('Gagal menghapus data pengguna : ' . substr($e->getMessage(), 0, 1000) . ' at ' . $e->getFile() . ' in line ' . $e->getLine());
            toastr()->error('Gagal menghapus pengguna !');
            DB::rollback();
        }
        return back();
    }
}

resources/views/admin/user/create.blade.php
@extends("layout.template")

@push('custom-css')
<style>
    .swal-modal{
        width: 375px !important;
    }
    .swal-footer{
        text-align: center !important;
    }
</style>
@endpush

@section('content')

@if (old())
  {{-- expr --}}
  {{-- @dd(old()) --}}
@endif
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                <h1>{{ (@$data) ? 'Ubah' : 'Buat' }} Pengguna</h1>
                </div>
            </div>
            </div><!-- /.container-fluid -->
        </section>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">

                        <div class="card">
                          <form action="{{ (@$data) ? route('users.edit.update', @$data->id) : route('users.add.store') }}" method="post" class="form-horizontal" enctype="multipart/form-data">
                            @csrf
                            <!-- /.card-header -->
                            <div class="card-body">
                              <div class="form-group row">
                                <label for="name" class="col-sm-2 col-form-label">Nama <span class="required-field-sign"></span></label>
                                <div class="col-sm-10">
                                  <input type="text" name="name" class="form-control" id="name" value="{{ (@$data->name) ?? old('name') }}" placeholder="Nama" required>
                                  {!! @$errors ? $errors->first('name', '<code><small>:message</small></code>') : '' !!}
                                    <span class="invalid-feedback" role="alert">
                                        <strong id="error-nama"></strong>
                                    </span>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="email" class="col-sm-2 col-form-label">Alamat Email <span class="required-field-sign"></span></label>
                                <div class="col-sm-10">
                                  <input type="email" name="email" class="form-control" value="{{ (@$data->email) ?? old('email') }}" id="email" placeholder="Alamat Email" required>
                                  {!! @$errors ? $errors->first('email', '<code><small>:message</small></code>') : '' !!}
                                    <span class="invalid-feedback" role="alert">
                                        <strong id="error-email"></strong>
                                    </span>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="password" class="col-sm-2 col-form-label">Password {!! (@$data) ? '' : '<span class="required-field-sign"></span>' !!}</label>
                                <div class="col-sm-10">
                                      <div class="input-group">
                                          <input type="password" name="password" class="form-control border-right-0" id="password" placeholder="Password" {{ @$data ? '' : 'required' }}>
                                          <!-- <div class="input-group-append bg-white">
                                              <div class="btn border border-left-0" onclick="show_password()" id="show">
                                                <span class="fas fa-eye"></span>
                                              </div>
                                              <div class="btn border border-left-0" onclick="hide_password()" id="hide" hidden>
                                                <span class="fas fa-eye-slash"></span>
                                              </div>
                                          </div> -->
                                      </div>
                                  {!! @$errors ? $errors->first('password', '<code><small>:message</small></code>') : '' !!}
                                    <span class="invalid-feedback" role="alert">
                                        <strong id="error-password"></strong>
                                    </span>
                                </div>
                              </div>

                              <div class="form-group row">
                                <label for="password_confirmation" class="col-sm-2 col-form-label">Konfirm Password {!! (@$data) ? '' : '<span class="required-field-sign"></span>' !!}</label>
                                <div class="col-sm-10">
                                    <div class="input-group">
                                        <input type="password" name="password_confirmation" class="form-control border-right-0" id="password_confirmation" placeholder="Konfirm Password"  {{ @$data ? '' : 'required' }}>
                                        <!-- <div class="input-group-append bg-white">
                                            <div class="btn border border-left-0" onclick="show_password_confirmation()" id="show_form">
                                              <span class="fas fa-eye"></span>
                                            </div>
                                            <div class="btn border border-left-0" onclick="hide_password_confirmation()" id="hide_form" hidden>
                                              <span class="fas fa-eye-slash"></span>
                                            </div>
                                        </div> -->
                                    </div>
                                  {!! @$errors ? $errors->first('password_confirmation', '<code><small>:message</small></code>') : '' !!}
                                </div>
                              </div>
                            </div>

                            <div class="card-footer">
                              <a href="{{ route('users.index') }}" id="batal" class="btn btn-default">Batal</a>
                              <button type="submit" class="btn btn-primary">{{ (@$data) ? 'Ubah' : 'Simpan' }}</button>
                            </div>
                            <!-- /.card-body -->
                          </form>
                        </div>
                        <!-- /.card -->

                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
            </section>


    </div>

@endsection

@push('custom-scripts')
<script>
  $(document).ready(function(){
    function show() {
      $('#show').attr('hidden','true');
      $('#hide').removeAttr('hidden');
      $('#password').attr('type','text');
    }
    function hide() {
      $('#show').removeAttr('hidden');
      $('#hide').attr('hidden','true');
      $('#password').attr('type','password');
    }
    function show_password_confirmation() {
      $('#show_form').attr('hidden','true');
      $('#hide_form').removeAttr('hidden');
      $('#password_confirmation').attr('type','text');
    }
    function hide_password_confirmation() {
      $('#show_form').removeAttr('hidden');
      $('#hide_form').attr('hidden','true');
      $('#password_confirmation').attr('type','password');
    }
  });
</script>
@include("admin.user.script")
@endpush

resources/views/admin/user/index.blade.php
@extends("layout.template")

@push('custom-css')
<!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('template/') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('template/') }}/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('template/') }}/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <style>
        div.dataTables_wrapper div.dataTables_filter input {
            padding-right: 1%
        }
    </style>
@endpush

@section('content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                <h1>Data Pengguna</h1>
                </div>
            </div>
            </div><!-- /.container-fluid -->
        </section>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">

                        <div class="card">
                            @if (user()->roles_id != 2)
                                <div class="card-header">
                                    <div class="row">
                                        <a href="{{ route('users.add') }}" class="btn btn-success" id="btn-upload">
                                            <i class="fa fa-plus"></i> Buat Akun
                                        </a>
                                    </div>
                                </div>
                            @endif
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table id="user-table" class="table table-bordered table-striped" style="width: 100%">
                                <thead>
                                    <th>No</th>
                                    <th>Nama</th>
                                    <th>Alamat Email</th>
                                    <th>Tanggal dibuat</th>
                                    <th>Aksi</th>
                                </thead>
                                <tbody>
                                </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
            </section>


    </div>

@endsection

@push('custom-scripts')
@include("admin.user.script")
@endpush

resources/views/admin/user/script.blade.php
<!-- DataTables  & Plugins -->
<script src="{{ asset('template/') }}/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="{{ asset('template/') }}/plugins/jszip/jszip.min.js"></script>
<script src="{{ asset('template/') }}/plugins/pdfmake/pdfmake.min.js"></script>
<script src="{{ asset('template/') }}/plugins/pdfmake/vfs_fonts.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="{{ asset('template/') }}/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

<script>
$(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip();

  $('#user-table').DataTable({
    processing: true,
    "language": { "emptyTable": "Tidak ada data",
                  "searchPlaceholder": "Bedasarkan Nama atau Email",
                },
    serverSide: true,
    ajax: '{{ route("users.datatable") }}',
    columns: [
      {data: 'DT_RowIndex', name: 'no', orderable: false, searchable: false},
      {data: 'name', name: 'name'},
      {data: 'email', name: 'email'},
      {data: 'created_at', name: 'created_at', orderable: false, searchable: false},
      {data: 'action', name: 'action', orderable: false, searchable: false}
    ],
    initComplete: function(){
        var api = this.api();
        $('#user-table_filter input')
            .off('.DT')
            .on('keyup.DT', function (e) {
                if (e.keyCode == 13) {
                    api.search(this.value).draw();
                }
            });
      },
  });
});
</script>